### PR TITLE
revert: 4.0.0

### PR DESCRIPTION
**Pull request by Mercy811**
This reverts commit 4cd73b41826a5854da2d72f162194287b110d275.

It should be a minor version.

### CODE REVIEW

**Comment by yuhao900914** [comment]
Does this work?
We should also delete the release tag. 
But we already released the 4.0.0 in npm and it cannot be reverted there. What if in the future we want to bump to 4.0.0?

**Comment by Mercy811** [comment]
- Unpublish npm version by https://amplitude.atlassian.net/wiki/spaces/GOV/pages/2570715611/incident-2024-07-11-bad-npm-version#Actions
- Delete S3 object 
- Remote tag 


image

**Comment by Mercy811** [comment]
@yuhao900914, I delete the 4.0.0 tag, the next release will based on the last version 3.8.0

**Comment by yuhao900914** [comment]
@Mercy811  Thanks. Good to know. It's much better than maven.

**Review by yuhao900914 — APPROVED** [review]

**Comment by Mercy811** [comment]
@yuhao900914, to prevent this from happening again I'm also going to dadd a `release.yml` file to branch v3.x to create a publish v3.x like what we have publish 2.x in the typescript repo https://github.com/amplitude/Amplitude-TypeScript/actions/workflows/publish-v2.yml

**Pull request merged**
